var products = [
    {
        image: "sweatshirt.jpg",
        title: "WL Comet Hoodie",
        price: "$35.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets 2018 Football Hoodie",
        colors: ["Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1900"
    }, 
    {
        image: "comet ti-dye shirt.png",
        title: "WL Comet Tie-Dye T-Shirt",
        price: "$21.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Tie-Dye T-Shirt",
        colors: ["Blue and Light Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "women"],
        product_id: "C1901"
    }, 
    {
        image: "comet hat.jpg",
        title: "West Liberty Comet Hat",
        price: "$24.00",
        sizes: ["6 3/4", "6 3/8", "7", "7 3/4", "7 3/8"],
        description: "West Liberty Comets Hat",
        colors: ["Blue and White"],
        materials: ["100% Polleyester"],
        brand: "Nike",
        categories: ["men", "women", "youth"],
        product_id: "C1902"
    }, 
    {
        image: "west liberty comets 2019 hoodie.png",
        title: "WL Comet 2019 Sweatsirt",
        price: "$35.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets 2018",
        colors: ["Gray and Blue"],
        materials: ["100% Pollyester"],
        brand: "Nike",
        categories: ["men"],
        product_id: "C1903"
    }, 
    {
        image: "comet wrestling shirt.jpg",
        title: "WL Comet Wresling Shirt",
        price: "$21.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Wreslting Shirt",
        colors: ["Gray"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1904"
    }, 
    {
        image: "pullover swaetshirt.jpg",
        title: "WL Comet Pullover Sweatshirt",
        price: "$26.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Pullover Sweatshirt",
        colors: ["Royal Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1905"
    }, 
    {
        image: "womens jogger pants.png",
        title: "WL Comet Womens Jogger Pants",
        price: "$15.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comet Jogger Pants",
        colors: ["Black"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["women"],
        product_id: "C1906"
    }, 
    {
        image: "west liberty strong shirt.jpg",
        title: "WL Strong Shirt",
        price: "$23.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Strong Shirt",
        colors: ["White"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1907"
    }, 
    {
        image: "comet ti-dye sweatshirt.png",
        title: "WL Comet Tie-Dye Hoodie",
        price: "$36.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Ty-Dye Hoodie",
        colors: ["Blue and Light Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1908"
    }, 
    {
        image: "women united we stand shirt.jpg",
        title: "WL Comet United We Stand Shirt",
        price: "$20.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets United We Stand Shirt",
        colors: ["Gray"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["women"],
        product_id: "C1909"
    }, 
    {
        image: "class  of 2019 shirt.jpg",
        title: "WL Comet COF 2019 Shirt",
        price: "$21.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Class Of 2019",
        colors: ["White"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men"],
        product_id: "C1910"
    }, 
    {
        image: "comet t-shirt mens.png",
        title: "WL Comet Shirt",
        price: "$23.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comet Shirt",
        colors: ["Gray"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men"],
        product_id: "C1911"
    }, 
    {
        image: "comets sweatpants.png",
        title: "WL Comet Sweatpants",
        price: "$18.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comet Sweatpants",
        colors: ["Gray"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1912"
    }, 
    {
        image: "comets football jersey.png",
        title: "WL Comet Football Jersey",
        price: "$40.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comet Jersey",
        colors: ["Royal Blue"],
        materials: ["30% Cotton, 70% Polleyester"],
        brand: "Nike",
        categories: ["men", "women", "youth"],
        product_id: "C1913"
    }, 
    {
        image: "womens shorts.png",
        title: "WL Comets Womens Shorts",
        price: "$17.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Womens Shorts",
        colors: ["Black and White with Blue"],
        materials: ["100% Polleyester"],
        brand: "Nike",
        categories: ["women"],
        product_id: "C1914"
    }, 
    {
        image: "west liberty comet shorts.png",
        title: "WL Comet Shorts",
        price: "$16.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Shorts",
        colors: ["Royal Blue"],
        materials: ["100% Polleyester"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1915"
    }, 
    {
        image: "pullover.jpg",
        title: "WL Comets BB Hooded Pullover",
        price: "$20.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Basketball Hooded Pullover",
        colors: ["Royal Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1916"
    }, 
    {
        image: "womens shirt.png",
        title: "WL Womens Comet Shirt",
        price: "$20.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Womens Comet Shirt ",
        colors: ["Blue"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["women"],
        product_id: "C1917"
    }, 
    {
        image: "west liberty comets sweatshits.png",
        title: "WL Comet Hoodie",
        price: "$30.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Hoodie",
        colors: ["Blue, Black and Gray"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men"],
        product_id: "C1918"
    }, 
    {
        image: "shirt.jpg",
        title: "WL Comet Shirt",
        price: "$18.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "West Liberty Comets Shirt",
        colors: ["White"],
        materials: ["100% Cotton"],
        brand: "Nike",
        categories: ["men", "youth"],
        product_id: "C1919"
    }, 
    {
        image: "WLHS comet sweatshirt.jpg",
        title: "WLHS Hoodie",
        price: "$31.00",
        sizes: ["S", "M", "L", "XL", "XXL"],
        description: "WLHS Hoodie",
        colors: ["Blue faded Green"],
        materials: ["100% Cotton"],
        brand: "Gildan",
        categories: ["men", "youth"],
        product_id: "C1920"
    }
    ];